import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
const inter = Inter({ subsets: ["latin"] });
import { ModalProvider } from "@/components/providers/modal-provider";
import { PusherProvider } from "@/components/providers/pusher-provider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      
    <html lang="en">
      <body className={inter.className}  >
      <PusherProvider>
          {children}
          <ModalProvider/>
          </PusherProvider>
        
        </body>
    </html>
    </ClerkProvider>
  );
}
